[package]
name = "mtime-spk"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
mtime-core = { path = "../mtime-core" }
mtime-astro = { path = "../mtime-astro" }
mtime-jpl = { path = "../mtime-jpl" }
mtime-timescales = { path = "../mtime-timescales" }
mtime-eop = { path = "../mtime-eop" }
oxiephemeris-de = "0.1.1"

[lints]
workspace = true
