use mtime_core::{EvidenceState,QualityClass};
#[derive(Debug,Clone,Copy,PartialEq)]pub struct TextualTemporalReference{pub corpus:&'static str,pub reference:&'static str,pub concepts:&'static [&'static str],pub evidence:EvidenceState,pub quality:QualityClass,pub numerical_scientific_prior:Option<f64>,pub note:&'static str}
pub const TEMPORAL_ONTOLOGY:&[TextualTemporalReference]=&[
TextualTemporalReference{corpus:"Qur'an",reference:"2:189",concepts:&["hilal","mawaqit","people","hajj"],evidence:EvidenceState::TextualReference,quality:QualityClass::Conceptual,numerical_scientific_prior:None,note:"New moons/hilal connected conceptually with appointed times and Hajj."},
TextualTemporalReference{corpus:"Qur'an",reference:"10:5",concepts:&["sun","moon","manazil","years","hisab"],evidence:EvidenceState::TextualReference,quality:QualityClass::Conceptual,numerical_scientific_prior:None,note:"Celestial order, lunar stages, years and reckoning."},
TextualTemporalReference{corpus:"Qur'an",reference:"55:5",concepts:&["sun","moon","reckoning"],evidence:EvidenceState::TextualReference,quality:QualityClass::Conceptual,numerical_scientific_prior:None,note:"Sun and Moon associated with reckoning."},
TextualTemporalReference{corpus:"Qur'an",reference:"21:33",concepts:&["sun","moon","falak","motion"],evidence:EvidenceState::TextualReference,quality:QualityClass::Conceptual,numerical_scientific_prior:None,note:"Celestial motion/falak."},
TextualTemporalReference{corpus:"Torah / Hebrew Bible witness",reference:"Genesis 1:14",concepts:&["luminaries","signs","appointed-times","days","years"],evidence:EvidenceState::TextualReference,quality:QualityClass::Conceptual,numerical_scientific_prior:None,note:"Comparative textual concept only."},
TextualTemporalReference{corpus:"Psalms witness",reference:"Psalm 104:19",concepts:&["moon","appointed-times"],evidence:EvidenceState::TextualReference,quality:QualityClass::Conceptual,numerical_scientific_prior:None,note:"Comparative textual concept only."},
TextualTemporalReference{corpus:"Gospel witness",reference:"Mark 13:32",concepts:&["day","hour","epistemic-limit"],evidence:EvidenceState::TextualReference,quality:QualityClass::Conceptual,numerical_scientific_prior:None,note:"Epistemic-limit ontology only; not chronology prediction."}];
#[must_use]pub fn any_numerical_prior()->bool{TEMPORAL_ONTOLOGY.iter().any(|x|x.numerical_scientific_prior.is_some())}
#[cfg(test)]mod tests{use super::*;#[test]fn texts_cannot_supply_scientific_priors(){assert!(!any_numerical_prior());for r in TEMPORAL_ONTOLOGY{assert_eq!(r.evidence,EvidenceState::TextualReference);assert_eq!(r.quality,QualityClass::Conceptual);}}}
