[package]
name="mtime-solar-provider"
version.workspace=true
edition.workspace=true
license.workspace=true

[dependencies]
solar-ephemeris="=0.2.0"
serde_json="1"
mtime-core={path="../mtime-core"}
mtime-astro={path="../mtime-astro"}
mtime-hijri={path="../mtime-hijri"}
mtime-eop={path="../mtime-eop"}
mtime-timescales={path="../mtime-timescales"}
