use mtime_core::{EarthObserver,TemporalError};

#[derive(Debug,Clone,Copy,PartialEq,Eq)]pub enum Body{Sun,Moon}
#[derive(Debug,Clone,Copy,PartialEq)]pub struct EquatorialState{pub right_ascension_deg:f64,pub declination_deg:f64,pub distance_au:f64}
#[derive(Debug,Clone,Copy,PartialEq)]pub struct EclipticState{pub longitude_deg:f64,pub latitude_deg:f64,pub distance_au:f64}
pub trait EphemerisProvider{fn id(&self)->&'static str;fn equatorial(&self,body:Body,jd_tt:f64)->Result<EquatorialState,TemporalError>;fn ecliptic(&self,body:Body,jd_tt:f64)->Result<EclipticState,TemporalError>;}
#[derive(Debug,Clone,Copy,PartialEq)]pub struct ApparentHorizonState{pub altitude_deg:f64,pub azimuth_deg:f64,pub refraction_applied:bool}
#[must_use]pub fn wrap_degrees(x:f64)->f64{x.rem_euclid(360.0)}
#[must_use]pub fn angular_separation_deg(a:EquatorialState,b:EquatorialState)->f64{let ra1=a.right_ascension_deg.to_radians();let ra2=b.right_ascension_deg.to_radians();let d1=a.declination_deg.to_radians();let d2=b.declination_deg.to_radians();(d1.sin()*d2.sin()+d1.cos()*d2.cos()*(ra1-ra2).cos()).clamp(-1.0,1.0).acos().to_degrees()}
#[must_use]pub fn gmst_deg(jd_ut1:f64)->f64{let t=(jd_ut1-2_451_545.0)/36_525.0;wrap_degrees(280.460_618_37+360.985_647_366_29*(jd_ut1-2_451_545.0)+0.000_387_933*t*t-t*t*t/38_710_000.0)}
pub fn topocentric_horizon(state:EquatorialState,observer:EarthObserver,jd_ut1:f64)->Result<ApparentHorizonState,TemporalError>{if !jd_ut1.is_finite(){return Err(TemporalError::NonFinite);}let lst=wrap_degrees(gmst_deg(jd_ut1)+observer.longitude_deg);let h=wrap_degrees(lst-state.right_ascension_deg);let hs=if h>180.0{h-360.0}else{h};let lat=observer.latitude_deg.to_radians();let dec=state.declination_deg.to_radians();let hr=hs.to_radians();let alt=(lat.sin()*dec.sin()+lat.cos()*dec.cos()*hr.cos()).clamp(-1.0,1.0).asin();let y=-hr.sin()*dec.cos();let x=dec.sin()*lat.cos()-dec.cos()*lat.sin()*hr.cos();Ok(ApparentHorizonState{altitude_deg:alt.to_degrees(),azimuth_deg:wrap_degrees(y.atan2(x).to_degrees()),refraction_applied:false})}
pub fn geocentric_elongation_deg<P:EphemerisProvider>(provider:&P,jd_tt:f64)->Result<f64,TemporalError>{Ok(angular_separation_deg(provider.equatorial(Body::Sun,jd_tt)?,provider.equatorial(Body::Moon,jd_tt)?))}
#[derive(Debug,Clone,Copy)]pub struct FixedEphemeris{pub sun_eq:EquatorialState,pub moon_eq:EquatorialState,pub sun_ecl:EclipticState,pub moon_ecl:EclipticState}
impl EphemerisProvider for FixedEphemeris{fn id(&self)->&'static str{"FIXED_TEST_EPHEMERIS"}fn equatorial(&self,body:Body,_:f64)->Result<EquatorialState,TemporalError>{Ok(match body{Body::Sun=>self.sun_eq,Body::Moon=>self.moon_eq})}fn ecliptic(&self,body:Body,_:f64)->Result<EclipticState,TemporalError>{Ok(match body{Body::Sun=>self.sun_ecl,Body::Moon=>self.moon_ecl})}}
#[cfg(test)]mod tests{use super::*;#[test]fn identical_states_have_zero_separation(){let a=EquatorialState{right_ascension_deg:10.0,declination_deg:-5.0,distance_au:1.0};assert!(angular_separation_deg(a,a)<1e-7);}#[test]fn horizon_is_finite(){let s=EquatorialState{right_ascension_deg:120.0,declination_deg:5.0,distance_au:1.0};let o=EarthObserver::new(106.8,-6.3,50.0).unwrap();let h=topocentric_horizon(s,o,2_460_000.5).unwrap();assert!(h.altitude_deg.is_finite()&&h.azimuth_deg.is_finite());}}
