use mtime_core::{EvidenceState,Provenance,QualityClass};

#[derive(Debug,Clone,PartialEq)]pub struct HijriAstronomicalState{pub conjunction_jd_tt:Option<f64>,pub sunset_jd_ut1:Option<f64>,pub moon_altitude_topocentric_deg:f64,pub elongation_geocentric_deg:f64,pub moon_age_hours:Option<f64>,pub moon_lag_minutes:Option<f64>,pub site_id:String,pub ephemeris_source:String,pub quality:QualityClass}
#[derive(Debug,Clone,Copy,PartialEq,Eq)]pub enum Comparator{GreaterOrEqual,GreaterThan,LessOrEqual,LessThan}
#[derive(Debug,Clone,Copy,PartialEq,Eq)]pub enum Metric{MoonAltitudeTopocentricDeg,ElongationGeocentricDeg,MoonAgeHours,MoonLagMinutes}
#[derive(Debug,Clone,PartialEq)]pub struct ThresholdClause{pub id:&'static str,pub metric:Metric,pub comparator:Comparator,pub threshold:f64,pub unit:&'static str}
#[derive(Debug,Clone,PartialEq)]pub struct ClauseResult{pub clause_id:&'static str,pub actual:Option<f64>,pub threshold:f64,pub passed:Option<bool>,pub reason:String}
#[derive(Debug,Clone,Copy,PartialEq,Eq)]pub enum RuleIfNotMet{CompleteCurrentMonthTo30Days,NoAutomaticCalendarOutcome}
#[derive(Debug,Clone,PartialEq)]pub struct CalendarProfile{pub id:&'static str,pub version:&'static str,pub effective_from:&'static str,pub effective_through:Option<&'static str>,pub clauses:Vec<ThresholdClause>,pub require_all:bool,pub if_not_met:RuleIfNotMet,pub observation_is_separate:bool,pub authority_is_separate:bool,pub provenance:Provenance}
impl CalendarProfile{
#[must_use]pub fn mabims_indonesia_2026()->Self{Self{id:"MABIMS_ID_2026",version:"PMA_1_2026",effective_from:"2026-01-01",effective_through:None,clauses:vec![ThresholdClause{id:"ALTITUDE_TOPOCENTRIC_GE_3",metric:Metric::MoonAltitudeTopocentricDeg,comparator:Comparator::GreaterOrEqual,threshold:3.0,unit:"deg"},ThresholdClause{id:"ELONGATION_GEOCENTRIC_GE_6_4",metric:Metric::ElongationGeocentricDeg,comparator:Comparator::GreaterOrEqual,threshold:6.4,unit:"deg"}],require_all:true,if_not_met:RuleIfNotMet::CompleteCurrentMonthTo30Days,observation_is_separate:true,authority_is_separate:true,provenance:Provenance{source:"Kementerian Agama RI, PMA No. 1 Tahun 2026".into(),source_version:Some("PMA-1-2026".into()),retrieved_at:None}}}
#[must_use]pub fn evaluate(&self,state:&HijriAstronomicalState)->CriterionResult{let clauses=self.clauses.iter().map(|c|evaluate_clause(c,state)).collect::<Vec<_>>();let known=clauses.iter().all(|x|x.passed.is_some());let met=known&&if self.require_all{clauses.iter().all(|x|x.passed==Some(true))}else{clauses.iter().any(|x|x.passed==Some(true))};CriterionResult{profile_id:self.id,profile_version:self.version,met:if known{Some(met)}else{None},clauses,if_not_met:self.if_not_met,evidence:EvidenceState::Calculated}}
}
fn metric_value(metric:Metric,state:&HijriAstronomicalState)->Option<f64>{match metric{Metric::MoonAltitudeTopocentricDeg=>Some(state.moon_altitude_topocentric_deg),Metric::ElongationGeocentricDeg=>Some(state.elongation_geocentric_deg),Metric::MoonAgeHours=>state.moon_age_hours,Metric::MoonLagMinutes=>state.moon_lag_minutes}}
fn evaluate_clause(c:&ThresholdClause,state:&HijriAstronomicalState)->ClauseResult{let actual=metric_value(c.metric,state);let passed=actual.map(|v|match c.comparator{Comparator::GreaterOrEqual=>v>=c.threshold,Comparator::GreaterThan=>v>c.threshold,Comparator::LessOrEqual=>v<=c.threshold,Comparator::LessThan=>v<c.threshold});ClauseResult{clause_id:c.id,actual,threshold:c.threshold,passed,reason:match(actual,passed){(None,_)=>"metric unavailable".into(),(Some(v),Some(true))=>format!("{v:.6} {} passes threshold {:.6}",c.unit,c.threshold),(Some(v),Some(false))=>format!("{v:.6} {} fails threshold {:.6}",c.unit,c.threshold),_=>"unknown".into()}}}
#[derive(Debug,Clone,PartialEq)]pub struct CriterionResult{pub profile_id:&'static str,pub profile_version:&'static str,pub met:Option<bool>,pub clauses:Vec<ClauseResult>,pub if_not_met:RuleIfNotMet,pub evidence:EvidenceState}
#[derive(Debug,Clone,Copy,PartialEq,Eq)]pub enum ComputedMonthAction{BeginNewMonthNextLocalDay,CompleteCurrentMonthTo30Days,AwaitAdditionalRuleOrObservation,Unknown}
#[must_use]pub fn computed_action(result:&CriterionResult)->ComputedMonthAction{match result.met{Some(true)=>ComputedMonthAction::BeginNewMonthNextLocalDay,Some(false)if result.if_not_met==RuleIfNotMet::CompleteCurrentMonthTo30Days=>ComputedMonthAction::CompleteCurrentMonthTo30Days,Some(false)=>ComputedMonthAction::AwaitAdditionalRuleOrObservation,None=>ComputedMonthAction::Unknown}}
#[cfg(test)]mod tests{use super::*;fn state(a:f64,e:f64)->HijriAstronomicalState{HijriAstronomicalState{conjunction_jd_tt:None,sunset_jd_ut1:None,moon_altitude_topocentric_deg:a,elongation_geocentric_deg:e,moon_age_hours:None,moon_lag_minutes:None,site_id:"TEST".into(),ephemeris_source:"fixture".into(),quality:QualityClass::Reference}}#[test]fn mabims_requires_both_thresholds(){let p=CalendarProfile::mabims_indonesia_2026();assert_eq!(p.evaluate(&state(3.0,6.4)).met,Some(true));assert_eq!(p.evaluate(&state(2.99,7.0)).met,Some(false));assert_eq!(p.evaluate(&state(5.0,6.39)).met,Some(false));}#[test]fn failure_completes_month(){let r=CalendarProfile::mabims_indonesia_2026().evaluate(&state(1.0,5.0));assert_eq!(computed_action(&r),ComputedMonthAction::CompleteCurrentMonthTo30Days);}#[test]fn observation_and_authority_are_separate(){let p=CalendarProfile::mabims_indonesia_2026();assert!(p.observation_is_separate&&p.authority_is_separate);}}
