export const EVIDENCE_STATES=Object.freeze(['OBSERVED','MEASURED','CALCULATED','MODELED','INFERRED','RECONSTRUCTED','SPECULATIVE','TEXTUAL_REFERENCE']);
export const CONCEPTUAL_GRAPH=Object.freeze(['CREATION','MEASURE','CELESTIAL_MOTION','FALAK','CYCLE','HISAB','CHRONOLOGY','OBSERVATION','MODEL','VALIDATION','UNCERTAINTY','KNOWLEDGE_BOUNDARY']);
export const COSMOLOGY_PIPELINE=Object.freeze(['OBSERVATION','PARAMETERS','PHYSICAL_MODEL','EXPANSION_HISTORY','NUMERICAL_INTEGRATION','COSMIC_AGE_DISTRIBUTION','UNCERTAINTY','VALIDATION']);
