import { inferCosmicAge,einsteinDeSitterAnalyticAgeSeconds,flatMatterLambdaAnalyticAgeSeconds } from './age.js';
import { hubbleKmSmpcToSI } from './parameters.js';
import { getCosmologyPreset,materializePresetParameters } from './references.js';
const relError=(a,b)=>Math.abs(a-b)/Math.max(Math.abs(b),Number.MIN_VALUE);
export function validateH0Dimensions(H0=70){const si=hubbleKmSmpcToSI(H0);return{H0,H0SI:si,hubbleTimeSeconds:1/si,pass:si>1e-19&&si<1e-16};}
export function validateEinsteinDeSitter({H0=70,tolerance=1e-8}={}){const numeric=inferCosmicAge('flat-lcdm',{H0,omegaR:0,omegaM:1,omegaLambda:0},{normalization:{flatnessTolerance:1e-12,consistencyMode:'reject'}}),analytic=einsteinDeSitterAnalyticAgeSeconds(H0),error=relError(numeric.result.seconds,analytic);return{numeric:numeric.result.seconds,analytic,relativeError:error,pass:error<=tolerance};}
export function validateFlatMatterLambda({H0=70,omegaM=.3,tolerance=1e-8}={}){const omegaLambda=1-omegaM,numeric=inferCosmicAge('flat-lcdm',{H0,omegaR:0,omegaM,omegaLambda},{normalization:{flatnessTolerance:1e-12,consistencyMode:'reject'}}),analytic=flatMatterLambdaAnalyticAgeSeconds({H0,omegaM,omegaLambda}),error=relError(numeric.result.seconds,analytic);return{numeric:numeric.result.seconds,analytic,relativeError:error,pass:error<=tolerance};}
export function validatePlanckSanity({toleranceGyr=.05}={}){const preset=getCosmologyPreset('planck2018'),params=materializePresetParameters(preset),result=inferCosmicAge(preset.model,params,{parameterSource:preset.id,observationalSource:preset.provenance.dataset}),delta=result.result.gyr-preset.publishedAgeGyr.mean;return{computedGyr:result.result.gyr,published:preset.publishedAgeGyr,deltaGyr:delta,pass:Math.abs(delta)<=toleranceGyr};}
export function integrationStability(model,parameters){const settings=[{absoluteTolerance:1e-8,relativeTolerance:1e-8},{absoluteTolerance:1e-10,relativeTolerance:1e-10},{absoluteTolerance:1e-12,relativeTolerance:1e-12}],results=settings.map(integration=>inferCosmicAge(model,parameters,{integration}).result.gyr),span=Math.max(...results)-Math.min(...results);return{settings,results,spanGyr:span,pass:span<1e-6};}
export function phaseAgeDegeneracy(period,phase,nA=1,nB=10){if(!(period>0)||!Number.isFinite(phase))throw new RangeError('invalid period/phase');const tA=(phase+nA)*period,tB=(phase+nB)*period;return{phase,period,tA,tB,samePhaseModuloPeriod:Math.abs(((tA-tB)/period)-Math.round((tA-tB)/period))<1e-12,absoluteAgeDetermined:false};}
export function rejectAntikytheraBigBangSemanticMisuse(claim){const s=String(claim).toLowerCase();if(s.includes('antikythera')&&(s.includes('big bang')||s.includes('age of the universe')||s.includes('umur semesta')))throw new Error('SEMANTIC_BOUNDARY: Antikythera cycles encode recurrence/phase, not the Big Bang date or cosmic age.');return true;}
