[package]
name = "mtime-clock"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
mtime-core = { path = "../mtime-core" }
mtime-timescales = { path = "../mtime-timescales" }
mtime-antikythera = { path = "../mtime-antikythera" }
mtime-temporal = { path = "../mtime-temporal" }
mtime-uncertainty = { path = "../mtime-uncertainty" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[lints]
workspace = true
